name: Build
on:
  push:
    paths:
      - .github/workflows/build.yml
      - package.json
      - scripts/build/**.mts
      - src/**.[cm]?ts
  pull_request:
    paths:
      - .github/workflows/build.yml
      - package.json
      - scripts/build/**.mts
      - src/**.[cm]?ts

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 6
      matrix:
        build_type: [electron, types]
        include:
          - build_type: browser
            extra_command: |
              pnpm run lint:mv2
              pnpm run lint:mv3

    name: Build ${{ matrix.build_type }}
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x.x

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Get PNPM version from package.json
        id: pnpm-version
        shell: bash
        run: echo "pnpm_version=$(node -p 'require(`./package.json`).packageManager.replace(`pnpm@`, ``)')" >> $GITHUB_OUTPUT

      - name: Set up pnpm
        uses: pnpm/action-setup@v3
        with:
          version: ${{ steps.pnpm-version.outputs.pnpm_version }}
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_OUTPUT

      - name: Set up pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH  }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Build ${{ matrix.build_type }}
        run: pnpm run build ${{ matrix.build_type }}

      - if: matrix.extra_command
        run: ${{ matrix.extra_command }}

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.build_type }}
          path: dist/*
